#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub lexeme: String,
    pub line: usize,
    pub column: usize,
}

#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    Int(i64),
    Float(f64),
    Char(char),
    String(String),
    Ident(String),
    KwIf,
    KwElse,
    KwWhile,
    KwFor,
    KwReturn,
    KwStruct,
    KwExport,
    KwImport,
    KwConst,
    KwUnique,
    KwMove,
    KwFree,
    KwAlloc,
    KwNull,
    KwTrue,
    KwFalse,
    KwVoid,
    KwExtern,
    KwUnsafe,
    KwAs,
    KwStatic,
    KwClone,
    KwAsm,
    KwBreak,
    KwContinue,
    OpPlus,
    OpMinus,
    OpStar,
    OpSlash,
    OpPercent,
    OpAssign,
    OpEq,
    OpNe,
    OpLt,
    OpGt,
    OpLe,
    OpGe,
    OpAnd,
    OpOr,
    OpNot,
    OpBitAnd,
    OpBitOr,
    OpBitXor,
    OpBitNot,
    OpShl,
    OpShr,
    OpInc,
    OpDec,
    OpArrow,
    OpScope,
    OpQuestion,
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Comma,
    Semicolon,
    Colon,
    Dot,
    Pound,
    PpImport,
    PpInclude,
    PpDefine,
    PpIfdef,
    PpIfndef,
    PpEndif,
    Eof,
}

impl TokenKind {
    pub fn from_keyword(s: &str) -> Option<TokenKind> {
        match s {
            "if" => Some(TokenKind::KwIf),
            "else" => Some(TokenKind::KwElse),
            "while" => Some(TokenKind::KwWhile),
            "for" => Some(TokenKind::KwFor),
            "return" => Some(TokenKind::KwReturn),
            "struct" => Some(TokenKind::KwStruct),
            "export" => Some(TokenKind::KwExport),
            "import" => Some(TokenKind::KwImport),
            "const" => Some(TokenKind::KwConst),
            "unique" => Some(TokenKind::KwUnique),
            "move" => Some(TokenKind::KwMove),
            "free" => Some(TokenKind::KwFree),
            "alloc" => Some(TokenKind::KwAlloc),
            "null" => Some(TokenKind::KwNull),
            "true" => Some(TokenKind::KwTrue),
            "false" => Some(TokenKind::KwFalse),
            "void" => Some(TokenKind::KwVoid),
            "extern" => Some(TokenKind::KwExtern),
            "unsafe" => Some(TokenKind::KwUnsafe),
            "as" => Some(TokenKind::KwAs),
            "static" => Some(TokenKind::KwStatic),
            "clone" => Some(TokenKind::KwClone),
            "asm" => Some(TokenKind::KwAsm),
            "break" => Some(TokenKind::KwBreak),
            "continue" => Some(TokenKind::KwContinue),
            _ => None,
        }
    }
}
