#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub lexeme: String,
    pub line: usize,
    pub column: usize,
}

#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    Int(i64),
    Float(f64),
    Char(char),
    String(String),
    Ident(String),
    KwIf,
    KwElse,
    KwWhile,
    KwFor,
    KwReturn,
    KwStruct,
    KwExport,
    KwImport,
    KwConst,
    KwUnique,
    KwMove,
    KwFree,
    KwAlloc,
    KwNull,
    KwTrue,
    KwFalse,
    KwVoid,
    KwExtern,
    KwUnsafe,
    KwAs,
    KwStatic,
    KwClone,
    KwAsm,
    KwBreak,
    KwContinue,
    OpPlus,
    OpMinus,
    OpStar,
    OpSlash,
    OpPercent,
    OpAssign,
    OpEq,
    OpNe,
    OpLt,
    OpGt,
    OpLe,
    OpGe,
    OpAnd,
    OpOr,
    OpNot,
    OpBitAnd,
    OpBitOr,
    OpBitXor,
    OpBitNot,
    OpShl,
    OpShr,
    OpInc,
    OpDec,
    OpArrow,
    OpScope,
    OpQuestion,
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Comma,
    Semicolon,
    Colon,
    Dot,
    Pound,
    PpImport,
    PpInclude,
    PpDefine,
    PpIfdef,
    PpIfndef,
    PpEndif,
    Eof,
}

impl TokenKind {
    pub fn from_keyword(s: &str) -> Option<TokenKind> {
        match s {
            "if" => Some(TokenKind::KwIf),
            "else" => Some(TokenKind::KwElse),
            "while" => Some(TokenKind::KwWhile),
            "for" => Some(TokenKind::KwFor),
            "return" => Some(TokenKind::KwReturn),
            "struct" => Some(TokenKind::KwStruct),
            "export" => Some(TokenKind::KwExport),
            "import" => Some(TokenKind::KwImport),
            "const" => Some(TokenKind::KwConst),
            "unique" => Some(TokenKind::KwUnique),
            "move" => Some(TokenKind::KwMove),
            "free" => Some(TokenKind::KwFree),
            "alloc" => Some(TokenKind::KwAlloc),
            "null" => Some(TokenKind::KwNull),
            "true" => Some(TokenKind::KwTrue),
            "false" => Some(TokenKind::KwFalse),
            "void" => Some(TokenKind::KwVoid),
            "extern" => Some(TokenKind::KwExtern),
            "unsafe" => Some(TokenKind::KwUnsafe),
            "as" => Some(TokenKind::KwAs),
            "static" => Some(TokenKind::KwStatic),
            "clone" => Some(TokenKind::KwClone),
            "asm" => Some(TokenKind::KwAsm),
            "break" => Some(TokenKind::KwBreak),
            "continue" => Some(TokenKind::KwContinue),
            _ => None,
        }
    }

    /// Stable name used by `--dump-tokens` output. Mirrors `uc_token_kind_name`
    /// in the C port (src-c/src/token.c) so the two compilers can be diffed
    /// directly.
    pub fn name(&self) -> &'static str {
        match self {
            TokenKind::Int(_) => "Int",
            TokenKind::Float(_) => "Float",
            TokenKind::Char(_) => "Char",
            TokenKind::String(_) => "String",
            TokenKind::Ident(_) => "Ident",

            TokenKind::KwIf => "KwIf",
            TokenKind::KwElse => "KwElse",
            TokenKind::KwWhile => "KwWhile",
            TokenKind::KwFor => "KwFor",
            TokenKind::KwReturn => "KwReturn",
            TokenKind::KwStruct => "KwStruct",
            TokenKind::KwExport => "KwExport",
            TokenKind::KwImport => "KwImport",
            TokenKind::KwConst => "KwConst",
            TokenKind::KwUnique => "KwUnique",
            TokenKind::KwMove => "KwMove",
            TokenKind::KwFree => "KwFree",
            TokenKind::KwAlloc => "KwAlloc",
            TokenKind::KwNull => "KwNull",
            TokenKind::KwTrue => "KwTrue",
            TokenKind::KwFalse => "KwFalse",
            TokenKind::KwVoid => "KwVoid",
            TokenKind::KwExtern => "KwExtern",
            TokenKind::KwUnsafe => "KwUnsafe",
            TokenKind::KwAs => "KwAs",
            TokenKind::KwStatic => "KwStatic",
            TokenKind::KwClone => "KwClone",
            TokenKind::KwAsm => "KwAsm",
            TokenKind::KwBreak => "KwBreak",
            TokenKind::KwContinue => "KwContinue",

            TokenKind::OpPlus => "OpPlus",
            TokenKind::OpMinus => "OpMinus",
            TokenKind::OpStar => "OpStar",
            TokenKind::OpSlash => "OpSlash",
            TokenKind::OpPercent => "OpPercent",
            TokenKind::OpAssign => "OpAssign",
            TokenKind::OpEq => "OpEq",
            TokenKind::OpNe => "OpNe",
            TokenKind::OpLt => "OpLt",
            TokenKind::OpGt => "OpGt",
            TokenKind::OpLe => "OpLe",
            TokenKind::OpGe => "OpGe",
            TokenKind::OpAnd => "OpAnd",
            TokenKind::OpOr => "OpOr",
            TokenKind::OpNot => "OpNot",
            TokenKind::OpBitAnd => "OpBitAnd",
            TokenKind::OpBitOr => "OpBitOr",
            TokenKind::OpBitXor => "OpBitXor",
            TokenKind::OpBitNot => "OpBitNot",
            TokenKind::OpShl => "OpShl",
            TokenKind::OpShr => "OpShr",
            TokenKind::OpInc => "OpInc",
            TokenKind::OpDec => "OpDec",
            TokenKind::OpArrow => "OpArrow",
            TokenKind::OpScope => "OpScope",
            TokenKind::OpQuestion => "OpQuestion",

            TokenKind::LParen => "LParen",
            TokenKind::RParen => "RParen",
            TokenKind::LBrace => "LBrace",
            TokenKind::RBrace => "RBrace",
            TokenKind::LBracket => "LBracket",
            TokenKind::RBracket => "RBracket",
            TokenKind::Comma => "Comma",
            TokenKind::Semicolon => "Semicolon",
            TokenKind::Colon => "Colon",
            TokenKind::Dot => "Dot",
            TokenKind::Pound => "Pound",

            TokenKind::PpImport => "PpImport",
            TokenKind::PpInclude => "PpInclude",
            TokenKind::PpDefine => "PpDefine",
            TokenKind::PpIfdef => "PpIfdef",
            TokenKind::PpIfndef => "PpIfndef",
            TokenKind::PpEndif => "PpEndif",

            TokenKind::Eof => "Eof",
        }
    }
}
